# Generated by Django 2.1.1 on 2018-10-07 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cvv_otp_check', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardimage',
            name='image_path',
        ),
    ]
