# Generated by Django 2.1.1 on 2018-10-07 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cvv_otp_check', '0002_remove_cardimage_image_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardimage',
            name='card_no',
        ),
        migrations.DeleteModel(
            name='CardImage',
        ),
    ]
