# Generated by Django 2.1.1 on 2018-10-07 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvv_otp_check', '0003_auto_20181007_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCardDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('cvc', models.CharField(max_length=3)),
                ('mm', models.CharField(max_length=2)),
                ('yyyy', models.CharField(max_length=4)),
            ],
        ),
        migrations.DeleteModel(
            name='CreditCard',
        ),
    ]
