# Generated by Django 2.1.1 on 2018-10-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvv_otp_check', '0004_auto_20181007_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcarddetails',
            name='number',
            field=models.CharField(max_length=16),
        ),
    ]
