# Generated by Django 2.1.1 on 2018-10-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvv_otp_check', '0006_auto_20181009_0014'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('Id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('number', models.BigIntegerField()),
                ('name', models.CharField(max_length=50)),
                ('cvc', models.SmallIntegerField()),
                ('mm', models.SmallIntegerField()),
                ('yyyy', models.SmallIntegerField()),
                ('Phone', models.BigIntegerField()),
                ('otp', models.SmallIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='CreditCardDetails',
        ),
    ]
